export class BlockArrayDetail {
    constructor(private Id,
        private blkNme,
        private blocktype,
        private noofunits,
        private mngName,
        private BlockManagermobile,
        private manageremail,
        private rate,
        private rate1,
        private meter,
        private frequency,
        private billGenerationDate,
        private dueDate,
        private latePymtChargeType,
        private latePymtCharge,
        private startsFrom,
        private flatRatevalue,
        private maintenanceValue,
        private flatRate,
        private dimension,
        private uniqueID,
        private valid
        ){}
}
