export class NotificationListArray {
    constructor(private unUniName,
        private asAsnName,
        private ntMobile,
        private ufName,
        private adminEntryImg,
        private unOcStat,
        private occupiedBy,
        private ownername,
        private uMobile,
        private admincollapse,
        private adminNtid,
        private AdmNtIsActive,
        private adminReadStatus,
        private sbRoleID,
        private sbMemID,
        private sbUnitID,
        private sbSubID,
        private mrRolName,
        private asAssnID,
        private unSldDate,
        private unOcSDate,
        private acNotifyID,
        private ntType,
        private adminNtdCreated,
        private acAccntID){}
}
