export class ResidentNotificationListArray {
    constructor(
        private vlComName,
        private vlVisType,
        private asAsnName,
        private vlApprdBy,
        private vlMobile,
        private unUniName,
        private vldCreated,
        private vlengName,
        private visitorEntryImg,
        private collapse,
        private NtType,
        private vlExAprdBy,
        private vlApprStat,
        private vlexgName,
        private residentNtid,
        private RsdntNtIsActive,
        private residentReadStatus,
        private residentNtdCreated,
        private vlVisLgID,
        private asAssnID,
        private vlfName,
        private vlExitT,
        private approvedBy,
        private ntDesc,
        private wkDesgn,
        private wkName,
        private sbUnitID,
        private ntType,
        private ntJoinStat,
        private WrUniName,
        private acNotifyID,
        private visitorlog
        ){}
        
}
